### PR TITLE
mokutil:check the result of malloc() is necessary

### PR DESCRIPTION
**Pull request by GYShit**
Signed-off-by: gaoyusong <gaoyusong2@huawei.com>

### CODE REVIEW

**Comment by GYShit** [comment]
@lcp

**Comment by GYShit** [comment]
> @lcp

plz

**Comment by GYShit** [comment]
> @lcp

plz, help review the code

**Comment by lcp** [comment]
Sorry for the delay. Got stuck with other stuff.
The patch looks good to me.

**Pull request merged**
